---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: cloudwatches.config.istio.io
  labels:
    app: mixer
    package: cloudwatch
    istio: mixer-adapter
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: config.istio.io
  names:
    kind: cloudwatch
    plural: cloudwatches
    singular: cloudwatch
    categories:
    - istio-io
    - policy-istio-io
  scope: Namespaced
  version: v1alpha2
