---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: dogstatsds.config.istio.io
  labels:
    app: mixer
    package: dogstatsd
    istio: mixer-adapter
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: config.istio.io
  names:
    kind: dogstatsd
    plural: dogstatsds
    singular: dogstatsd
    categories:
    - istio-io
    - policy-istio-io
  scope: Namespaced
  version: v1alpha2
