---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cleanup-secrets-istio-system
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: '1'
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - delete
