---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: zipkins.config.istio.io
  labels:
    app: mixer
    package: zipkin
    istio: mixer-adapter
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: config.istio.io
  names:
    kind: zipkin
    plural: zipkins
    singular: zipkin
    categories:
    - istio-io
    - policy-istio-io
  scope: Namespaced
  version: v1alpha2
