---
apiVersion: v1
kind: Service
metadata:
  name: istio-citadel
  namespace: istio-system
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
    istio: citadel
spec:
  ports:
  - name: grpc-citadel
    port: 8060
    targetPort: 8060
    protocol: TCP
  - name: http-monitoring
    port: 15014
  selector:
    istio: citadel
