---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-cleanup-secrets-1.1.5
  namespace: istio-system
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: '3'
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
spec:
  template:
    metadata:
      name: istio-cleanup-secrets
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
    spec:
      serviceAccountName: istio-cleanup-secrets-service-account
      containers:
      - name: kubectl
        image: docker.io/istio/kubectl:1.1.5
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - "kubectl get secret --all-namespaces | grep \"istio.io/key-and-cert\" |\
          \  while read -r entry; do\n  ns=$(echo $entry | awk '{print $1}');\n  name=$(echo\
          \ $entry | awk '{print $2}');\n  kubectl delete secret $name -n $ns;\ndone\n"
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
