---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: stdio
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer
    heritage: Tiller
    release: istio
spec:
  compiledAdapter: stdio
  params:
    outputAsJson: true
