---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-grafana
  namespace: istio-system
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
    istio: grafana
data:
  datasources.yaml: "apiVersion: 1\ndatasources:\n- access: proxy\n  editable: true\n\
    \  isDefault: true\n  jsonData:\n    timeInterval: 5s\n  name: Prometheus\n  orgId:\
    \ 1\n  type: prometheus\n  url: http://prometheus:9090\n"
  dashboardproviders.yaml: "apiVersion: 1\nproviders:\n- disableDeletion: false\n\
    \  folder: istio\n  name: istio\n  options:\n    path: /var/lib/grafana/dashboards/istio\n\
    \  orgId: 1\n  type: file\n"
