---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: stdiotcp
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer
    heritage: Tiller
    release: istio
spec:
  match: context.protocol == "tcp"
  actions:
  - handler: stdio
    instances:
    - tcpaccesslog.logentry
