apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpbin
  labels:
    foo: bar
spec:
  selector:
    matchLabels:
      name: foobar
  template:
    metadata:
      labels:
        name: foobar
    spec:
      containers:
        - image: "gcr.io/google-samples/hello-app:2.0"
          name: httpbin
          env:
          - name: "PORT"
            value: "50000"
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
